/**
 * LIVE DATA OVERRIDES — generated snapshot, not hand-written.
 *
 * This file is regenerated by exporting from the production database
 * (see packages/db/src/ingest-geography.mjs for the ingest, and the
 * export query in packages/db/INGEST.md). It is deliberately a plain
 * static object — imported synchronously, with zero runtime dependency
 * on the database.
 *
 * WHY A GENERATED SNAPSHOT INSTEAD OF A LIVE DB QUERY AT REQUEST TIME:
 *
 *   1. Every area page is statically generated (generateStaticParams).
 *      Making that async-dependent on a live DB connection at build time
 *      would mean the Docker build fails if the database is briefly
 *      unreachable during a deploy — a needless new failure mode.
 *   2. The blog engine calls getAllAreas() synchronously at MODULE LOAD
 *      to build its post index. Converting the whole call chain to async
 *      touches ~10 files across the app for a single-team, low-frequency
 *      data refresh. Not worth the risk this session.
 *   3. A snapshot is trivially inspectable in a PR diff — you can see
 *      exactly which numbers changed before they go live, the same
 *      discipline as the content-override system in the CMS.
 *
 * TO REFRESH: run the ingest, re-export, replace this file.
 *
 * ── WHAT'S ACTUALLY LIVE IN THIS SNAPSHOT ──
 *
 * Geography ONLY (lat/lng), sourced from postcodes.io (OGL v3), verified
 * against real ONS-derived coordinates for all 38 areas.
 *
 * scoreConfidence is 0.0 for every entry — deliberately below the
 * scoring engine's 0.60 publication threshold — because amenities, green
 * space and transport dimensions are NOT yet populated. Diagnosed
 * 2026-08-16: the public OpenStreetMap Overpass API (both overpass-api.de
 * and the kumi.systems mirror) actively rejects or throttles requests
 * from this server's IP:
 *
 *   overpass-api.de        → HTTP 406 (even with correct headers)
 *   overpass.kumi.systems  → HTTP 429, then HTTP 504 once a User-Agent
 *                             was added
 *
 * The free public Overpass API is built for occasional interactive
 * queries, not automated production ingestion from a datacenter IP.
 * NEXT SOURCE TO WIRE: a paid geodata API (Geoapify, TravelTime) or a
 * self-hosted Overpass instance.
 *
 * realvianScore stays null here — the mergeLive() function in areas.ts
 * correctly falls back to the seed composite score when confidence is
 * below threshold, so the headline score a visitor sees is unaffected.
 * What DOES change: the map coordinate (lat/lng) is now the real ONS
 * centroid rather than an estimate, and isLiveData() returns true for
 * these 38 outcodes so the UI badge is honest about partial coverage.
 *
 * Last generated: 2026-08-16
 */

export interface LiveAreaOverride {
  outcode: string;
  realvianScore: number | null;
  scoreConfidence: number;
  scoringVersion: string;
  amenityScore: number | null;
  greenSpaceScore: number | null;
  transportScore: number | null;
  lat: number;
  lng: number;
  lastRefreshedAt: string;
}

export const LIVE_GENERATED_AT: string | null = "2026-08-16";

export const LIVE_OVERRIDES: Record<string, LiveAreaOverride> = {
  "B13": {
    outcode: "B13",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 52.43771,
    lng: -1.87867,
    lastRefreshedAt: "2026-08-16",
  },
  "B14": {
    outcode: "B14",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 52.41733,
    lng: -1.88983,
    lastRefreshedAt: "2026-08-16",
  },
  "B15": {
    outcode: "B15",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 52.46629,
    lng: -1.92328,
    lastRefreshedAt: "2026-08-16",
  },
  "B17": {
    outcode: "B17",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 52.46125,
    lng: -1.95873,
    lastRefreshedAt: "2026-08-16",
  },
  "B5": {
    outcode: "B5",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 52.46888,
    lng: -1.89766,
    lastRefreshedAt: "2026-08-16",
  },
  "BS3": {
    outcode: "BS3",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.43868,
    lng: -2.6032,
    lastRefreshedAt: "2026-08-16",
  },
  "BS6": {
    outcode: "BS6",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.47079,
    lng: -2.60049,
    lastRefreshedAt: "2026-08-16",
  },
  "BS8": {
    outcode: "BS8",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.45748,
    lng: -2.62233,
    lastRefreshedAt: "2026-08-16",
  },
  "BS9": {
    outcode: "BS9",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.48726,
    lng: -2.62678,
    lastRefreshedAt: "2026-08-16",
  },
  "CF11": {
    outcode: "CF11",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.47288,
    lng: -3.19249,
    lastRefreshedAt: "2026-08-16",
  },
  "CF5": {
    outcode: "CF5",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.48331,
    lng: -3.24546,
    lastRefreshedAt: "2026-08-16",
  },
  "E17": {
    outcode: "E17",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.58696,
    lng: -0.02084,
    lastRefreshedAt: "2026-08-16",
  },
  "EH15": {
    outcode: "EH15",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 55.94616,
    lng: -3.11254,
    lastRefreshedAt: "2026-08-16",
  },
  "EH3": {
    outcode: "EH3",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 55.95188,
    lng: -3.20682,
    lastRefreshedAt: "2026-08-16",
  },
  "EH4": {
    outcode: "EH4",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 55.96267,
    lng: -3.26218,
    lastRefreshedAt: "2026-08-16",
  },
  "EH6": {
    outcode: "EH6",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 55.97254,
    lng: -3.17514,
    lastRefreshedAt: "2026-08-16",
  },
  "G12": {
    outcode: "G12",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 55.88056,
    lng: -4.30059,
    lastRefreshedAt: "2026-08-16",
  },
  "G3": {
    outcode: "G3",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 55.86571,
    lng: -4.27806,
    lastRefreshedAt: "2026-08-16",
  },
  "G41": {
    outcode: "G41",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 55.83767,
    lng: -4.28435,
    lastRefreshedAt: "2026-08-16",
  },
  "KY16": {
    outcode: "KY16",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 56.34258,
    lng: -2.82367,
    lastRefreshedAt: "2026-08-16",
  },
  "L17": {
    outcode: "L17",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.37764,
    lng: -2.94054,
    lastRefreshedAt: "2026-08-16",
  },
  "LS2": {
    outcode: "LS2",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.80257,
    lng: -1.54565,
    lastRefreshedAt: "2026-08-16",
  },
  "LS6": {
    outcode: "LS6",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.82012,
    lng: -1.57083,
    lastRefreshedAt: "2026-08-16",
  },
  "LS7": {
    outcode: "LS7",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.82073,
    lng: -1.53987,
    lastRefreshedAt: "2026-08-16",
  },
  "LS8": {
    outcode: "LS8",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.82478,
    lng: -1.50947,
    lastRefreshedAt: "2026-08-16",
  },
  "M19": {
    outcode: "M19",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.43641,
    lng: -2.19623,
    lastRefreshedAt: "2026-08-16",
  },
  "M20": {
    outcode: "M20",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.42421,
    lng: -2.2327,
    lastRefreshedAt: "2026-08-16",
  },
  "M21": {
    outcode: "M21",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.43801,
    lng: -2.27293,
    lastRefreshedAt: "2026-08-16",
  },
  "M33": {
    outcode: "M33",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.42099,
    lng: -2.32637,
    lastRefreshedAt: "2026-08-16",
  },
  "M4": {
    outcode: "M4",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.48505,
    lng: -2.23015,
    lastRefreshedAt: "2026-08-16",
  },
  "N8": {
    outcode: "N8",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.58313,
    lng: -0.11974,
    lastRefreshedAt: "2026-08-16",
  },
  "NE2": {
    outcode: "NE2",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 54.98706,
    lng: -1.60596,
    lastRefreshedAt: "2026-08-16",
  },
  "NE6": {
    outcode: "NE6",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 54.97751,
    lng: -1.56582,
    lastRefreshedAt: "2026-08-16",
  },
  "NE7": {
    outcode: "NE7",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 55.00027,
    lng: -1.57975,
    lastRefreshedAt: "2026-08-16",
  },
  "SE15": {
    outcode: "SE15",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.47283,
    lng: -0.06557,
    lastRefreshedAt: "2026-08-16",
  },
  "SW11": {
    outcode: "SW11",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.46875,
    lng: -0.16284,
    lastRefreshedAt: "2026-08-16",
  },
  "TW9": {
    outcode: "TW9",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 51.46961,
    lng: -0.29238,
    lastRefreshedAt: "2026-08-16",
  },
  "WA14": {
    outcode: "WA14",
    realvianScore: null,
    scoreConfidence: 0.0,
    scoringVersion: "geo-only-1.0",
    amenityScore: null,
    greenSpaceScore: null,
    transportScore: null,
    lat: 53.38787,
    lng: -2.36095,
    lastRefreshedAt: "2026-08-16",
  },
};
