"use client";

import { useState } from "react";
import type { Area } from "@/lib/areas";

const PRIMARY: [number, number, number] = [14, 166, 114];
const INFO: [number, number, number] = [45, 91, 255];
const MUTED: [number, number, number] = [138, 147, 163];
const INK: [number, number, number] = [15, 23, 32];
const BORDER: [number, number, number] = [226, 232, 238];

interface SavedComparisonWithAreas {
  id: string;
  createdAt: string;
  a: Area;
  b: Area;
}

interface FollowedAreaWithArea {
  id: string;
  createdAt: string;
  area: Area;
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}

/**
 * Same client-side jsPDF approach as the other five PDF exports on
 * this site — deliberately reused, not re-invented. Combines both
 * saved comparisons and followed areas into one document, since both
 * live on the same account page and someone downloading a personal
 * summary would want both, not two separate files.
 */
export function AccountSummaryPdfExport({
  comparisons,
  followed,
}: {
  comparisons: SavedComparisonWithAreas[];
  followed: FollowedAreaWithArea[];
}) {
  const [generating, setGenerating] = useState(false);
  const isEmpty = comparisons.length === 0 && followed.length === 0;

  async function downloadPdf() {
    setGenerating(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const bottomLimit = pageHeight - 22;
      let y = 24;

      function ensureSpace(needed: number) {
        if (y + needed > bottomLimit) {
          doc.addPage();
          y = 24;
        }
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...PRIMARY);
      doc.text("REALVIAN", margin, y);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      doc.text("Account Summary", pageWidth - margin, y, { align: "right" });
      y += 14;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(19);
      doc.setTextColor(...INK);
      doc.text("Your saved areas and comparisons", margin, y);
      y += 12;

      if (comparisons.length > 0) {
        ensureSpace(10);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(...INK);
        doc.text(`Saved comparisons (${comparisons.length})`, margin, y);
        y += 9;

        for (const c of comparisons) {
          ensureSpace(9);
          doc.setFont("helvetica", "bold");
          doc.setFontSize(10);
          doc.setTextColor(...PRIMARY);
          doc.text(String(c.a.realvianScore), margin, y);
          doc.setTextColor(...INK);
          doc.text(c.a.district, margin + 10, y);

          doc.setFont("helvetica", "normal");
          doc.setTextColor(...MUTED);
          doc.text("vs", margin + 70, y);

          doc.setFont("helvetica", "bold");
          doc.setTextColor(...INFO);
          doc.text(String(c.b.realvianScore), margin + 80, y);
          doc.setTextColor(...INK);
          doc.text(c.b.district, margin + 90, y);

          doc.setFont("helvetica", "normal");
          doc.setFontSize(8.5);
          doc.setTextColor(...MUTED);
          doc.text(`Saved ${fmtDate(c.createdAt)}`, pageWidth - margin, y, { align: "right" });
          y += 8;
        }
        y += 6;
      }

      if (followed.length > 0) {
        ensureSpace(10);
        doc.setDrawColor(...BORDER);
        doc.line(margin, y, pageWidth - margin, y);
        y += 9;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(...INK);
        doc.text(`Followed areas (${followed.length})`, margin, y);
        y += 9;

        for (const f of followed) {
          ensureSpace(9);
          doc.setFont("helvetica", "bold");
          doc.setFontSize(10);
          doc.setTextColor(...PRIMARY);
          doc.text(String(f.area.realvianScore), margin, y);
          doc.setTextColor(...INK);
          doc.text(`${f.area.district}, ${f.area.city}`, margin + 10, y);

          doc.setFont("helvetica", "normal");
          doc.setFontSize(8.5);
          doc.setTextColor(...MUTED);
          doc.text(`Followed ${fmtDate(f.createdAt)}`, pageWidth - margin, y, { align: "right" });
          y += 8;
        }
      }

      const pageCount = doc.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        doc.setPage(p);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(...MUTED);
        doc.text(
          `Generated by realvian.co.uk on ${new Date().toLocaleDateString("en-GB")} \u00b7 realvian.co.uk/account`,
          margin,
          pageHeight - 12,
        );
        doc.text(`Page ${p} of ${pageCount}`, pageWidth - margin, pageHeight - 12, { align: "right" });
        doc.text(
          "Illustrative figures where noted \u2014 not financial advice. Verify independently before making a purchase decision.",
          margin,
          pageHeight - 8,
        );
      }

      doc.save("realvian-account-summary.pdf");
    } finally {
      setGenerating(false);
    }
  }

  return (
    <button
      type="button"
      onClick={downloadPdf}
      disabled={generating || isEmpty}
      className="inline-flex items-center gap-2 px-4 py-2 rounded-[var(--radius-md)] border border-[var(--border)] text-[13.5px] font-medium text-[var(--text-primary)] hover:border-[var(--border-strong)] transition-colors disabled:opacity-60"
    >
      <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      {generating ? "Generating…" : "Download account summary PDF"}
    </button>
  );
}
