"use client";

import { useState } from "react";

const PRIMARY: [number, number, number] = [14, 166, 114];
const MUTED: [number, number, number] = [138, 147, 163];
const INK: [number, number, number] = [15, 23, 32];
const BORDER: [number, number, number] = [226, 232, 238];

export interface CalcPdfRow {
  label: string;
  value: string;
  emphasis?: boolean;
}

/**
 * Same client-side jsPDF approach as the other seven PDF exports on
 * this site — deliberately reused, not re-invented. One generic
 * component shared by all four calculators (mortgage, stamp duty,
 * yield, ROI) rather than four near-identical ones: each calculator
 * already computes its own inputs and results in its own local
 * state, so it just hands this component the current numbers as
 * plain label/value rows.
 */
export function CalculatorPdfExport({
  title,
  inputs,
  results,
  disclaimer,
  filenameSlug,
}: {
  title: string;
  inputs: CalcPdfRow[];
  results: CalcPdfRow[];
  disclaimer: string;
  filenameSlug: string;
}) {
  const [generating, setGenerating] = useState(false);

  async function downloadPdf() {
    setGenerating(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      let y = 24;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...PRIMARY);
      doc.text("REALVIAN", margin, y);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      doc.text("Calculator", pageWidth - margin, y, { align: "right" });
      y += 14;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(19);
      doc.setTextColor(...INK);
      doc.text(title, margin, y);
      y += 12;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(...MUTED);
      doc.text("YOUR FIGURES", margin, y);
      y += 8;
      for (const row of inputs) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(...INK);
        doc.text(row.label, margin, y);
        doc.setFont("helvetica", "bold");
        doc.text(row.value, pageWidth - margin, y, { align: "right" });
        y += 7;
      }

      y += 4;
      doc.setDrawColor(...BORDER);
      doc.line(margin, y, pageWidth - margin, y);
      y += 10;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(...MUTED);
      doc.text("RESULT", margin, y);
      y += 8;
      for (const row of results) {
        doc.setFont("helvetica", row.emphasis ? "bold" : "normal");
        doc.setFontSize(row.emphasis ? 12 : 10);
        doc.setTextColor(...(row.emphasis ? PRIMARY : INK));
        doc.text(row.label, margin, y);
        doc.text(row.value, pageWidth - margin, y, { align: "right" });
        y += row.emphasis ? 9 : 7;
      }

      y += 6;
      doc.setDrawColor(...BORDER);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      const discLines = doc.splitTextToSize(disclaimer, pageWidth - margin * 2);
      doc.text(discLines, margin, y);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text(
        `Generated by realvian.co.uk on ${new Date().toLocaleDateString("en-GB")} \u00b7 realvian.co.uk/tools`,
        margin,
        pageHeight - 12,
      );

      doc.save(`realvian-${filenameSlug}-calculation.pdf`);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <button
      type="button"
      onClick={downloadPdf}
      disabled={generating}
      className="print-hide inline-flex items-center gap-2 px-3.5 py-1.5 rounded-[var(--radius-sm)] border border-[var(--border)] text-[12.5px] font-medium text-[var(--text-primary)] hover:border-[var(--border-strong)] transition-colors disabled:opacity-60"
    >
      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      {generating ? "Generating…" : "Download PDF"}
    </button>
  );
}
