"use client";

import { useState } from "react";
import type { Area } from "@/lib/areas";
import { fmtPrice, fmtYield, fmtPct } from "@/lib/areas";

const PRIMARY: [number, number, number] = [14, 166, 114];
const MUTED: [number, number, number] = [138, 147, 163];
const INK: [number, number, number] = [15, 23, 32];
const BORDER: [number, number, number] = [226, 232, 238];

/**
 * Same client-side jsPDF approach as the other three PDF exports on
 * this site (area, comparison, report) — deliberately reused, not
 * re-invented, same reasoning each time (no new server-side rendering
 * dependency). This one exports whatever the investor has actually
 * filtered to right now, not the full unfiltered dataset, so the
 * criteria used matter and are printed at the top of the report.
 */
export function ShortlistPdfExport({
  areas,
  minYield,
  maxPrice,
  city,
}: {
  areas: Area[];
  minYield: number;
  maxPrice: number;
  city: string;
}) {
  const [generating, setGenerating] = useState(false);

  async function downloadPdf() {
    setGenerating(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const bottomLimit = pageHeight - 22;
      let y = 24;

      function ensureSpace(needed: number) {
        if (y + needed > bottomLimit) {
          doc.addPage();
          y = 24;
        }
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...PRIMARY);
      doc.text("REALVIAN", margin, y);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      doc.text("Investment Shortlist", pageWidth - margin, y, { align: "right" });
      y += 12;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(19);
      doc.setTextColor(...INK);
      doc.text(`${areas.length} matching area${areas.length === 1 ? "" : "s"}`, margin, y);
      y += 8;

      // Search criteria, printed so the report is self-explanatory
      // later, not just a bare list with no context for why these
      // areas were included.
      const criteria: string[] = [];
      if (minYield > 0) criteria.push(`Min yield ${minYield}%`);
      if (maxPrice > 0) criteria.push(`Max price ${fmtPrice(maxPrice)}`);
      if (city) criteria.push(`City: ${city}`);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...MUTED);
      doc.text(criteria.length > 0 ? criteria.join("  \u00b7  ") : "No filters applied", margin, y);
      y += 10;

      doc.setDrawColor(...BORDER);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;

      const columns = ["Area", "Score", "Price", "Yield", "5-yr growth"];
      const colWidths = [52, 22, 34, 26, 30];
      const colX = [margin];
      for (let i = 0; i < colWidths.length - 1; i++) colX.push(colX[i]! + colWidths[i]!);

      ensureSpace(8);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      columns.forEach((col, i) => doc.text(col.toUpperCase(), colX[i]!, y));
      y += 5;
      doc.setDrawColor(...BORDER);
      doc.line(margin, y, pageWidth - margin, y);
      y += 5;

      for (const area of areas) {
        ensureSpace(7);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...INK);
        doc.text(`${area.district}, ${area.city}`, colX[0]!, y);
        doc.text(String(area.realvianScore), colX[1]!, y);
        doc.text(fmtPrice(area.avgPrice), colX[2]!, y);
        doc.setTextColor(...PRIMARY);
        doc.text(fmtYield(area.grossYield), colX[3]!, y);
        doc.setTextColor(...INK);
        doc.text(fmtPct(area.fiveYearGrowth), colX[4]!, y);
        y += 7;
      }

      const pageCount = doc.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        doc.setPage(p);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(...MUTED);
        doc.text(
          `Generated by realvian.co.uk on ${new Date().toLocaleDateString("en-GB")} \u00b7 realvian.co.uk/portals/investor`,
          margin,
          pageHeight - 12,
        );
        doc.text(`Page ${p} of ${pageCount}`, pageWidth - margin, pageHeight - 12, { align: "right" });
        doc.text(
          "Illustrative figures where noted \u2014 not financial advice. Verify independently before making a purchase decision.",
          margin,
          pageHeight - 8,
        );
      }

      doc.save("realvian-investment-shortlist.pdf");
    } finally {
      setGenerating(false);
    }
  }

  return (
    <button
      type="button"
      onClick={downloadPdf}
      disabled={generating || areas.length === 0}
      className="inline-flex items-center gap-2 px-4 py-2 rounded-[var(--radius-md)] border border-[var(--border)] text-[13.5px] font-medium text-[var(--text-primary)] hover:border-[var(--border-strong)] transition-colors disabled:opacity-60"
    >
      <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      {generating ? "Generating…" : "Download shortlist PDF"}
    </button>
  );
}
